# Generated by Django 5.0.4 on 2024-05-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuser', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='user',
            name='carbos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fatos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='protos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
