# Generated by Django 5.0.4 on 2024-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuser', '0004_alter_meal_options_user_carbos_user_fatos_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muscle',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='physique',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='strength',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='carbos',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fatos',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='protos',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
